name: myproject ci
on: [push, pull]

jobs:
  build:
    runs-on: ubuntu-latest

  services: 
    postgres:
      image: postgres:13.2
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: github_actions
      ports:
        - 5432:5432
      options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

  steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
     
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
     
    - name: Coverage report
      run: |
        pip install coverage

        coverage run manage.py test --settings=hms.settings.testing

    - name: Run super-linter
      uses: github/super-linter@v4
        env:
          IGNORE_GITIGNORED_FILES: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



    - name: Django Testing
      run: |
        python manage.py test --settings=hms.settings.testing
